# Generated by Django 2.2.1 on 2019-09-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=512, null=True)),
                ('content_txt', models.TextField(null=True)),
                ('answer_idx', models.PositiveSmallIntegerField(default=1)),
                ('options1', models.TextField(blank=True, max_length=1024, null=True)),
                ('options2', models.TextField(blank=True, max_length=1024, null=True)),
                ('options3', models.TextField(blank=True, max_length=1024, null=True)),
                ('options4', models.TextField(blank=True, max_length=1024, null=True)),
                ('options5', models.TextField(blank=True, max_length=1024, null=True)),
                ('content_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('content_video', models.URLField(blank=True, null=True)),
                ('options6', models.TextField(blank=True, max_length=1024, null=True)),
                ('options7', models.TextField(blank=True, max_length=1024, null=True)),
                ('options8', models.TextField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(blank=True, max_length=512, null=True)),
                ('period', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('theme', models.CharField(blank=True, max_length=512, null=True)),
                ('point1', models.CharField(blank=True, max_length=512, null=True)),
                ('point2', models.CharField(blank=True, max_length=512, null=True)),
                ('point3', models.CharField(blank=True, max_length=512, null=True)),
                ('logic', models.CharField(blank=True, max_length=512, null=True)),
                ('difficult', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('subjects_set', models.ManyToManyField(to='SubjectsModel.Subject')),
            ],
        ),
    ]
