# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_set', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.PositiveIntegerField()),
                ('degree', models.PositiveSmallIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('content_txt', models.TextField()),
                ('content_img', models.ImageField(upload_to='')),
                ('content_video', models.URLField()),
                ('options', models.TextField()),
                ('answer_idx', models.PositiveSmallIntegerField()),
                ('created_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField()),
            ],
        ),
    ]
