# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='default', max_length=128),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content_txt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
