# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-18 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0002_auto_20190518_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subjects_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectsModel.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubjectsModel.Exam'),
        ),
    ]
