# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0004_auto_20190518_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subjects_set',
        ),
        migrations.AddField(
            model_name='exam',
            name='subjects_set',
            field=models.ManyToManyField(to='SubjectsModel.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='degree',
            field=models.PositiveSmallIntegerField(verbose_name='0-easy;5-normal;10-hard'),
        ),
    ]
