# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0009_auto_20190518_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attr1',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='attr2',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='attr3',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='degree',
            field=models.PositiveSmallIntegerField(verbose_name='Degree: 0-easy;5-normal;10-hard'),
        ),
    ]
