# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0010_auto_20190518_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='options',
            field=models.TextField(max_length=500),
        ),
    ]
