# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0011_auto_20190531_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='options',
        ),
        migrations.AddField(
            model_name='subject',
            name='options1',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options2',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options3',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options4',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options5',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options6',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options7',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='options8',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
