# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubjectsModel', '0012_auto_20190531_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='options1',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options2',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options3',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options4',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options5',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options6',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options7',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='options8',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
